Add operation definition profiles
HL7/crmi-ig pull request #24
Opened 2023-09-20 14:25 UTC by bkaney

This PR has the profiles for operation definitions, namely:

* Artifact Endpoint Configurable Operation
* Canonical Operation
* Data Configurable Operation
* Manifestable Operation
* Pagable Operation 
* VersionBindable Operation

And applies them to data-requirement and package operations.

TODO: @brynrhodes  
- Are "CRMI ValueSet Expand", and "CRMI Get Package" operations deprecated?
- I am not familiar with "release" operation, so I didn't update that in this PR

2023-10-11 15:12 UTC, bkaney commented on input/fsh/operation-profiles/versionable-operation-profile.fsh
> +Profile: VersionableOperation
```suggestion
Profile: VersionableBindableOperation
```

2023-10-11 15:12 UTC, bkaney commented on input/fsh/operation-profiles/versionable-operation-profile.fsh
> +Id: crmi-versionable-operation
```suggestion
Id: crmi-version-bindable-operation
```

2023-10-11 15:13 UTC, bkaney commented on input/fsh/operation-profiles/versionable-operation-profile.fsh
> +Title: "CRMI Operation Profile: Versionable"
```suggestion
Title: "CRMI Operation Profile: Version Bindable"
```

2023-10-11 15:13 UTC, bkaney commented on input/pages/operations.md
> +| [Versionable][2]                    | Defines parameters used to specify missing versions in canonical references |
```suggestion
| [Version Bindable][2]               | Defines parameters used to specify missing versions in canonical references |
```

2023-10-11 15:14 UTC, bkaney commented on input/pages/operations.md
> +[2]: StructureDefinition-crmi-versionable-operation.html
```suggestion
[2]: StructureDefinition-crmi-version-bindable-operation.html
```

2023-10-11 15:14 UTC, bkaney commented on input/fsh/metadata.fsh
> +RuleSet: VersionableOperationProfile
```suggestion
RuleSet: VersionBindableOperationProfile
```

2023-10-11 15:14 UTC, bkaney commented on input/fsh/metadata.fsh
> +* meta.profile[+] = Canonical(VersionableOperation)
```suggestion
* meta.profile[+] = Canonical(VersionBindableOperation)
```

2023-10-11 15:15 UTC, bkaney commented on input/fsh/operation-definitions/data-requirements-operation.fsh
> +* insert VersionableOperationProfile
```suggestion
* insert VersionBindableOperationProfile 
```

2023-10-11 15:15 UTC, bkaney commented on input/fsh/operation-definitions/package-operation.fsh
> +* insert VersionableOperationProfile
```suggestion
* insert VersionBindableOperationProfile 
```

2023-10-11 15:22 UTC, brynrhodes commented on input/fsh/operation-profiles/_shared.fsh
> +// also the "additional" canonical types
We should add a "ArtifactResourceTypes" that includes the CanonicalResourceTypes and the non-canonical definitional resource types

2023-10-11 15:25 UTC, brynrhodes commented on input/fsh/operation-profiles/canonical-operation-profile.fsh
> +Profile: CanonicalOperation
Rename this profile to ArtifactOperation

2023-10-11 15:30 UTC, brynrhodes commented on input/fsh/operation-profiles/versionable-operation-profile.fsh
> +Profile: VersionableBindableOperation
This becomes CanonicalVersionBindable operation, also create a new ArtifactVersionBindable operation that defines artifactVersion, checkArtifactVersion, and forceArtifactVersion parameters

2023-10-13 19:46 UTC, brynrhodes requested changes
A couple comments

2023-10-13 19:46 UTC, brynrhodes commented on input/fsh/operation-definitions/data-requirements-operation.fsh
This should be uri right, not boolean?

2023-10-13 19:46 UTC, brynrhodes commented on input/fsh/operation-definitions/data-requirements-operation.fsh
> +* parameter[+].name = #forceArtifactlVersion
forceArtfactVersion, not forceArtifactlVersion

2023-10-13 19:46 UTC, brynrhodes commented on input/fsh/operation-definitions/data-requirements-operation.fsh
> +* parameter[=].max = "1"
Needs to be * still, you can do this any number of times

2023-10-13 19:46 UTC, brynrhodes commented on input/fsh/operation-definitions/data-requirements-operation.fsh
> +* parameter[=].type = #boolean
Should be uri

2023-11-02 08:38 UTC, brynrhodes approved these changes

2023-11-02 08:39 UTC, merged